### ISSUE TITLE
Gas upper and lower limits

### ISSUE THREAD

**Issue by iabtyagi** [G6EJD/BME680-Example#1]
The upper and lower limits of gas resistance are mentioned as `50-50,000 ohms` in the README while, in your code, you have used different values:

```
int gas_lower_limit = 50000;   // Bad air quality limit
int gas_upper_limit = 500000;  // Good air quality limit 
```
Is this correct?
My sensor is giving output values in the range of 45,000 - 55,000 and I am using this code to get air quality. The air quality remains in 400+ range (hazardous).

**Comment by G6EJD** [comment]
Yes, when the code was updated recently the errors were introduced they should be 5,000 and 50,000 thanks for spotting that. Corrected now.

**Comment by iabtyagi** [comment]
Thanks!
Did you ever have to do burn-in of the sensor? Some say you need to burn-in the sensor for 20 minutes or so for the first time and 3-5 minutes every time you switch it on again.

**Comment by G6EJD** [comment]
No burn-in, but if you watch the readings you will see they change with multiple reads and the stabilise (assuming the conditions don't change). In my code example, that's why I periodically take more samples.
