### ISSUE TITLE
IAQ Readings inverse?

### ISSUE THREAD

**Issue by Chaot1** [G6EJD/BME680-Example#2]
Thank you for your great work.
But i have a small Problem with your Formula.
When i use the Formula i get at normal conditions a score 270, with open Window on fresh air 350 and with a Tissue full of perfume beside the Sensor 17.
When i try to use the IAQ Calculation i get a wrong result. Is that correcht or is my formula wrong?

**Comment by disruptex** [comment]
Good work with the code
But I think your code has a couple of challenges:
A. // Set up oversampling and filter initialization - is not set correctly
     My take Should be  - 
  bme.setTemperatureOversampling(BME680_OS_8X);
  bme.setHumidityOversampling(BME680_OS_2X);
  bme.setPressureOversampling(BME680_OS_4X);
  bme.setIIRFilterSize(BME680_FILTER_SIZE_3);
  bme.setGasHeater(320, 150); // 320*C for 150 ms
B. And I think the IAQ has some issues calcualting ....
if I can figure it out I will post it

**Comment by G6EJD** [comment]
Ok, but over sampling is a form of averaging and is a compromise between speed and gain in statistical spread, could be marginal gains. The IAQ index is a qualitative measurement that I explain in the github read me and is a combination of humidity and VOC, it could also include temperature like the Bosch index but that isn’t really air quality just heat. Good luck in making your adjustments.
