### ISSUE TITLE
calculation of iaq always zero

### ISSUE THREAD

**Issue by pabloandresm** [G6EJD/BME680-Example#3]
Hi,

I think you have a bug in lines 114 and 115, where you defined gas_lower_limit and gas_upper_limit as integers.

Then used in the following formulas with floats that makes the result zero.

You need to change those int to float too.

**Comment by G6EJD** [comment]
Yes, it was working with the ESP core 2.4.1 but I think casting of int to floats has changed, so I changed the types to float as you suggested, thanks.

**Comment by pabloandresm** [comment]
Thanks.

The problem was not only the float/int calculations, but also that an "int" in arduino is 16bits signed, so up to 32K....and you were initializing it to 50000

thanks for the quick fix.
pablo

**Comment by G6EJD** [comment]
Your right for the pure Arduino platforms such as the UNO, but on the ESP32 and ESP8266 an INT is 32-bits so OK.
