### ISSUE TITLE
GetGasReference average calculation

### ISSUE THREAD

**Issue by jp112sdl** [G6EJD/BME680-Example#5]
Hey!
Nice sketch, it helps me a lot!

I found something strange...
At first you declare the number of readings
https://github.com/G6EJD/BME680-Example/blob/82c057ef38de487b4e2853fcd1f54f3ec5827d1d/ESP32_bme680_CC_demo_02.ino#L137

...but iterate "number of readings + 1" (from 0 to 10 counts 11)
https://github.com/G6EJD/BME680-Example/blob/82c057ef38de487b4e2853fcd1f54f3ec5827d1d/ESP32_bme680_CC_demo_02.ino#L138

So the loop passes **11** times, but the cumulated gas_reference is divided by 10.
https://github.com/G6EJD/BME680-Example/blob/82c057ef38de487b4e2853fcd1f54f3ec5827d1d/ESP32_bme680_CC_demo_02.ino#L141

**Comment by G6EJD** [comment]
Yes your correct that’s a mistake it should be /(readings+1)

**Comment by G6EJD** [comment]
Corrected by counting for 10 not 11 samples.
