### ISSUE TITLE
gas_reference is never set to zero

### ISSUE THREAD

**Issue by jp112sdl** [G6EJD/BME680-Example#6]
You are cumulating `gas_reference` in the loop, but it is not set to zero before the loop.
So the value increases higher and higher...

https://github.com/G6EJD/BME680-Example/blob/b263e591c3c29342989bf240bd0599d2087252bc/ESP32_bme680_CC_demo_02.ino#L139

**Comment by G6EJD** [comment]
This enables the gas concentration to track changes in the environment as it’s not an absolute value. For example it may be quite normal for a city to have a normally high pollution level that rightly is treated as such, it’s only when the value climbs from that value that the change is detected and reported accordingly.

**Comment by G6EJD** [comment]
Also the bme680 takes so long to get a baseline gas reading about 20-30 mins that it’s not viable to get readings any faster than say once per day, maybe at 0900. It will take a long time to skew the readings.

**Comment by G6EJD** [comment]
And you’ve overlooked the lines:
if (gas_reference > gas_upper_limit) gas_reference = gas_upper_limit; 
  if (gas_reference < gas_lower_limit) gas_reference = gas_lower_limit;

That reset the gas reference value

**Comment by jp112sdl** [comment]
Ok... maybe `gas_reference` is set to `gas_upper_limit` which is **50000**.

Then, after 10 times of `loop()` you call `if ((getgasreference_count++)%10==0) GetGasReference(); `.

Remember: `gas_reference` is actual **50000**.

```
void GetGasReference(){
  // Now run the sensor for a burn-in period, then use combination of relative humidity and gas resistance to estimate indoor air quality as a percentage.
  Serial.println("Getting a new gas reference value");
  int readings = 10;
  for (int i = 1; i <= readings; i++){ // read gas for 10 x 0.150mS = 1.5secs
    gas_reference += bme.readGas();
  }
  gas_reference = gas_reference / readings;
}
```

Every time in `for...loop` you add the value from `bme.readGas();` to `gas_reference` __(which already comes with 50000 initially)__.

That means, you do _not_ calculate the average of the **10 readings**.
You're calculating the average of **(10 readings + the old gas_reference value)**.

I wondered why I always got to high values.


> Also the bme680 takes so long to get a baseline gas reading about 20-30 mins that it’s not viable to get readings any faster than say once per day, maybe at 0900. It will take a long time to skew the readings.

I think, I did not really understood the BME680. 
If I want to measure IAQ, why not call `bme.readGas()` every time?
My task is creating a device for the HomeMatic Smarthome system, that measures the current iaq every 3-5 minutes.

**Comment by G6EJD** [comment]
The bme680 takes time to stabilise gas resistance often many readings until it clears the sensor of humidity, as humidity affects the readings and don’t forgot a gas reading of 50,000 means the air is good.

**Comment by G6EJD** [comment]
I e just checked my algorithm and it works as expected, in my normal office environment the gas resistance is high >50,000 and then when I introduce the bme680 into a VOC environment the AQI droops then when I remove the bme680 back into clean air readings return to normal, but it’s an integrated reading so it takes time to react in both directions. I think you need to look at your test and operating design in a more holistic way.

**Comment by G6EJD** [comment]
Adafruit says this :
We recommend that you run this sensor for 48 hours when you first receive it to "burn it in", and then 30 minutes in the desired mode every time the sensor is in use. This is because the sensitivity levels of the sensor will change during early use, and the resistance will slowly rise over time as the MOX warms up to its baseline reading.
Which is how I run mine.

**Comment by jp112sdl** [comment]
Thanks for your clarification!

> We recommend that you run this sensor for 48 hours when you first receive it to "burn it in", and then 30 minutes in the desired mode every time the sensor is in use. 

But is a battery powered device possible at all?
For my understanding: Every time I want to do a `readGas` I have to do it for 30 minutes to get an accurate value?

**Comment by G6EJD** [comment]
This Is a problem with the device as 0.09‒12 mA for p/h/T/gas power consumption is too high for battery usage. If the gas reading is once per day then probably ok, it needs a mahr calculation to be undertaken to determine expected battery life. When measuring p/h/T current consumption is 3uA so ok for batteries, gas is the problem. There are lower power gas sensors around. Hence my comment about looking at the problem holistically.
