### ISSUE TITLE
gas_reference limits

### ISSUE THREAD

**Issue by tolot27** [G6EJD/BME680-Example#7]
With the current implementation you always set the gas_reference to its limits - every cycle of the loop. I'm unsure if that makes much sense. If yes, then move the "limiting" code to the function `GetGasReference()`. You can also change the uper and lower limits into global constants.

```C
  float gas_lower_limit = 5000;   // Bad air quality limit
  float gas_upper_limit = 50000;  // Good air quality limit 
  if (gas_reference > gas_upper_limit) gas_reference = gas_upper_limit; 
  if (gas_reference < gas_lower_limit) gas_reference = gas_lower_limit;
```

**Comment by tolot27** [comment]
Maybe you should initialize `gas_reference` with `gas_upper_limit` as well.

**Comment by G6EJD** [comment]
The code works perfectly, you could modify it for your own use. Have you used a bme680? The values are reset because it’s a rolling average and it takes approximately 30-mins to get a stable reading.
What aspects of the code is creating an issue when you use it please?

**Comment by tolot27** [comment]
My suggestion to move the limit checks to `GetGasReference()` is just an optimization regards to code size and time if it runs at a microcontroller. It does not make sense to me to execute his code every time in the loop when it can get called only once after `gas_reference` really changes.

I just found this during investigation of my problem that the air_quality_value lowers if the gas_resistance increases. Here is a test with some reactivator (solder paste, Sn97Cu3):

```
T: 25.18 degC, P: 953.41 hPa, H 49.05 %rH, G: 184849 ohms, IAQ: 18.85 (18.85)
T: 25.22 degC, P: 953.43 hPa, H 49.13 %rH, G: 181606 ohms, IAQ: 19.03 (19.03)
T: 25.34 degC, P: 953.41 hPa, H 49.64 %rH, G: 110196 ohms, IAQ: 20.08 (395.08)
T: 25.48 degC, P: 953.35 hPa, H 49.35 %rH, G: 104693 ohms, IAQ: 19.49 (394.49)
T: 25.64 degC, P: 953.35 hPa, H 48.59 %rH, G: 98881 ohms, IAQ: 17.90 (392.90)
T: 25.78 degC, P: 953.35 hPa, H 47.79 %rH, G: 106443 ohms, IAQ: 16.23 (391.23)
T: 25.92 degC, P: 953.31 hPa, H 47.04 %rH, G: 115017 ohms, IAQ: 14.67 (389.67)
T: 26.07 degC, P: 953.33 hPa, H 46.53 %rH, G: 122504 ohms, IAQ: 13.60 (388.60)
T: 26.22 degC, P: 953.31 hPa, H 46.19 %rH, G: 128193 ohms, IAQ: 12.89 (387.89)
T: 26.37 degC, P: 953.29 hPa, H 45.81 %rH, G: 131240 ohms, IAQ: 12.09 (387.09)
T: 26.52 degC, P: 953.29 hPa, H 45.48 %rH, G: 134984 ohms, IAQ: 11.41 (11.41)
T: 26.66 degC, P: 953.27 hPa, H 45.13 %rH, G: 136880 ohms, IAQ: 10.69 (10.69)
T: 26.82 degC, P: 953.25 hPa, H 44.71 %rH, G: 139532 ohms, IAQ: 9.81 (9.81)
T: 26.99 degC, P: 953.27 hPa, H 44.37 %rH, G: 57935 ohms, IAQ: 9.10 (384.10)
T: 27.12 degC, P: 953.27 hPa, H 44.38 %rH, G: 65444 ohms, IAQ: 9.11 (384.11)
T: 27.19 degC, P: 953.27 hPa, H 44.02 %rH, G: 74445 ohms, IAQ: 8.38 (383.38)
T: 27.24 degC, P: 953.25 hPa, H 43.68 %rH, G: 84988 ohms, IAQ: 7.67 (382.67)
T: 27.26 degC, P: 953.25 hPa, H 43.56 %rH, G: 95582 ohms, IAQ: 7.42 (382.42)
T: 27.26 degC, P: 953.25 hPa, H 43.49 %rH, G: 102301 ohms, IAQ: 7.26 (382.26)
T: 27.26 degC, P: 953.23 hPa, H 43.70 %rH, G: 106306 ohms, IAQ: 7.71 (382.71)
T: 27.26 degC, P: 953.25 hPa, H 44.04 %rH, G: 113597 ohms, IAQ: 8.41 (383.41)
T: 27.25 degC, P: 953.25 hPa, H 44.07 %rH, G: 118728 ohms, IAQ: 8.47 (383.47)
T: 27.24 degC, P: 953.25 hPa, H 44.00 %rH, G: 123601 ohms, IAQ: 8.33 (383.33)
T: 27.22 degC, P: 953.23 hPa, H 43.85 %rH, G: 126528 ohms, IAQ: 8.02 (383.02)
T: 27.21 degC, P: 953.27 hPa, H 43.90 %rH, G: 128691 ohms, IAQ: 8.14 (383.14)
T: 27.20 degC, P: 953.27 hPa, H 43.93 %rH, G: 131553 ohms, IAQ: 8.18 (383.18)
T: 27.19 degC, P: 953.25 hPa, H 43.90 %rH, G: 135647 ohms, IAQ: 8.12 (8.12)
T: 27.18 degC, P: 953.25 hPa, H 43.87 %rH, G: 135758 ohms, IAQ: 8.07 (8.07)
T: 27.17 degC, P: 953.21 hPa, H 43.80 %rH, G: 137220 ohms, IAQ: 7.92 (7.92)
```

The numbers in brackes are calculated acording to https://github.com/pimoroni/bme680-python/blob/master/examples/indoor-air-quality.py with a gas_reference of about 133000. As you can see, the IAQ get lower and lower where it should go up as the number in brackets.

**Comment by G6EJD** [comment]
I've updated the code to match changes in Gas Resistance returned by the Adafruit BME680 library, these have changed since I published the code some time back now.
We have to remember this is a qualitative index and so no two functions will ever (likely) return the same index values. There is no international reference for air quality for example. 
I've now test the revised code and it's working as I expect it.

**Comment by tolot27** [comment]
The limits now are now more appropriate. There is still something wrong, i. e. https://github.com/G6EJD/BME680-Example/blob/18d0c4bdabe06733e4e72c6e71397f5738445bf0/ESP32_bme680_CC_demo_03.ino#L106 where `score` is set to a fixed value.

**Comment by G6EJD** [comment]
I left that during testing, now removed.

**Comment by tolot27** [comment]
I think this issue can closed now.

I'm still think the reference function (`GetGasReference`) is called too frequent (every 10 seconds) and queries the gas values in a very short time which can result in incorrect values caused by self-heating.

If your air quality decreases steadily over a long time (i. e. two hours or more), the reference will be adjusted to this decrease and no worse IAQ score will be returned.

**Comment by G6EJD** [comment]
GetGasReference is called every 5-cycles about 15-secs, yes there is some self-heating but it takes a long time to get a stable reading. It’s more an example that a library function for final code embodiment.
