### ISSUE TITLE
demo_03 showing different result than 02

### ISSUE THREAD

**Issue by haldi4803** [G6EJD/BME680-Example#8]
Hi,

Using Demo_02 i get this result:
`------------------------------------------------
Temperature = 26.27°C
   Pressure = 947.98 hPa
   Humidity = 49.85%
        Gas = 95279R

Air Quality = 95.9% derived from 25% of Humidity reading and 75% of Gas reading - 100% is good quality air
Humidity element was : 0.21 of 0.25
     Gas element was : 0.75 of 0.75
***** Poor air quality *****

Air quality is Good
------------------------------------------------
`

With 03 and after a short while i get these results....
`--------------------------------------------------------------
Sensor Readings:
  Temperature = 26.19°C
     Pressure = 948.00 hPa
     Humidity = 49.7%
          Gas = 112987.19 ohms

Qualitative Air Quality Index  comprised of 20% Humidity and 26% Gas
IAQ Score = 270, air quality is Very Unhealthy
--------------------------------------------------------------
`

Because i was unsure of how the results i've put it outside in the cold:
7°C
65% Humidity
258kOhm R
105 AiQ

**Comment by G6EJD** [comment]
What are you saying is wrong with the algorithm? It’s been posted for a long time now and had many 200’s of downloads and no one has reported a fundamental error. Your problem is more likely to be a faulty sensor.

**Comment by ceaswaran** [comment]
Can you explain the difference between demo_03 & demo_02 code.
Thanks in advance.

**Comment by G6EJD** [comment]
The lower and upper gas limits were changed to reflect typical bme680 device values. Remember these are relative values and are indicative rather than being an absolute value as there is no standard reference to calibrate against.

**Comment by ceaswaran** [comment]
I am not an expert but I found something interesting /different while using above code both demo_03 & demo_02 w.r.t other open-source firmware 
1. Temperature , Humidity & Gas Pressure value seem to be in sync irrespective of any code/firmware.
2. BME 680 gas resistance while using the above code is in the order of 420000 Ohms
     Using Tasmota firmware, gas resistance is in the order of 151000 Ohm
    Using ESP Home  firmware, gas resistance is in the order of 15100 Ohm Only

Why there is a difference in gas resistance value alone & why?

**Comment by G6EJD** [comment]
How long are they heating the sensor for? You will find (according to the Bosch data sheet) that the device needs a minimum of 30-min warm-up time to produce a stable reading are you following their recommendations? Also a high gas resistance denotes good clean air, it sounds like all three approaches to obtaining an IAQ index are different which is why you have to use the measures as a qualitative measurement and not an absolute, what you need to do is use each algorithm and apply the same amount of VOC exposure and then see how each responds, then it is more likely you will see correlation in change ie all 3 show a similar per-unit change.

**Comment by G6EJD** [comment]
There are no code issues, the bme680 device is variable in its response and the results published are not from controlled conditions and in any event this is a qualitative index, so the individual results are meaningless and so I’m closing the issue.
